# This workflow will install Python dependencies and run the script gh_issues to generated a new repot
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Create GitHub Issues Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create artifact folder and copy index.html there
      run: |
        mkdir build_outputs_folder |
        cp ./index.html build_outputs_folder/index.html
    - name: Create a new GitHub issues report, sorted by days
      run: |
        python gh_issues.py -s days,user -f -a -n -t build_outputs_folder/report_days.html
    - name: Create a new GitHub issues report, sorted by user
      run: |
        python gh_issues.py -s user,days -f -a -n -t build_outputs_folder/report_user.html
    - name: Upload artifact folder to GitHub Pages
      # See https://github.com/actions/upload-pages-artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: build_outputs_folder/
  # See https://github.com/actions/deploy-pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
